version: "3"
services:
  db:
    container_name: mysql
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 3306:3306

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    depends_on:
      - db
    environment:
      KEYCLOAK_USER: "${KEYCLOAK_USER}"
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      MYSQL_DATABASE: keycloak
      MYSQL_USER: root
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 9990:9990
      - 8080:8080

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2018-03-12T21-25-28Z
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    ports:
      - 9000:9000
    command: server /data

  zoo1:
    container_name: zoo1
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ./zoo.1.cfg:/conf/zoo.cfg
      - zoo1-data:/data

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zoo1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181

volumes:
  db-data:
  minio-data:
  zoo1-data:
