version: "3"
services:
  db:
    container_name: mysql
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 3306:3306


  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    depends_on:
      - db
    environment:
      KEYCLOAK_USER: "${KEYCLOAK_USER}"
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      MYSQL_DATABASE: keycloak
      MYSQL_USER: root
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 9990:9990
      - 8080:8080

volumes:
  db-data:
